name: discover-movies

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - .env.dock
    depends_on:
      - db
      - redis

  db:
    image: postgres:17-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env.dock
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  redis:
    image: redis:alpine

  celery:
    build: .
    entrypoint: ""
    command: celery -A config worker -l info
    volumes:
      - .:/usr/src/app/
    depends_on:
      - redis

  celery-beat:
    build: .
    entrypoint: ""
    command: celery -A config beat -l info
    volumes:
      - .:/usr/src/app/
    depends_on:
      - redis

volumes:
  postgres-data:
