name: discover-movies

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    extra_hosts:
      - "api.themoviedb.org:18.161.6.19"
      - "image.tmdb.org:143.244.49.177"
      - "files.tmdb.org:108.157.254.49"
    volumes:
      - static-data:/home/app/web/static
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis

  db:
    image: postgres:17-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env.prod
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  redis:
    image: redis:alpine

  nginx:
    build: ./nginx
    volumes:
      - static-data:/home/app/web/static
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot/ --email ${EMAIL} --agree-tos --no-eff-email --non-interactive -d discovermovies.ru -d www.discovermovies.ru
    depends_on:
      - nginx

volumes:
  postgres-data:
  static-data:
