# Generated by Django 5.2.4 on 2025-07-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_genre_id', models.IntegerField(unique=True)),
                ('name', models.CharField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('logo_path', models.URLField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('imdb_id', models.CharField(blank=True, default='')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('original_title', models.CharField(blank=True, default='')),
                ('original_language', models.CharField(blank=True, default='')),
                ('spoken_languages', models.CharField(blank=True, default='')),
                ('overview', models.TextField(blank=True, default='')),
                ('tagline', models.TextField(blank=True, default='')),
                ('poster_path', models.URLField(blank=True, default='')),
                ('backdrop_path', models.URLField(blank=True, default='')),
                ('production_countries', models.CharField(blank=True, default='')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('Rumored', 'Rumored'),
                            ('Planned', 'Planned'),
                            ('In Production', 'In Production'),
                            ('Post Production', 'Post Production'),
                            ('Released', 'Released'),
                            ('Canceled', 'Canceled'),
                            ('undefined', 'undefined'),
                        ]
                    ),
                ),
                ('budget', models.PositiveIntegerField()),
                ('revenue', models.PositiveIntegerField()),
                ('runtime', models.PositiveIntegerField()),
                ('tmdb_popularity', models.PositiveIntegerField()),
                ('immdb_popularity', models.PositiveIntegerField(blank=True, null=True)),
                ('tmdb_rating', models.FloatField()),
                ('tmdb_vote_count', models.PositiveIntegerField()),
                ('lb_rating', models.FloatField(blank=True, null=True)),
                ('lb_vote_count', models.PositiveIntegerField(blank=True, null=True)),
                ('lb_fans', models.PositiveIntegerField(blank=True, null=True)),
                ('lb_watched', models.PositiveIntegerField(blank=True, null=True)),
                ('lb_liked', models.PositiveIntegerField(blank=True, null=True)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('imdb_vote_count', models.PositiveIntegerField(blank=True, null=True)),
                ('kp_rating', models.FloatField(blank=True, null=True)),
                ('kp_vote_count', models.PositiveIntegerField(blank=True, null=True)),
                ('genre_id', models.ManyToManyField(blank=True, null=True, to='moviedb.genre')),
                ('production_company_id', models.ManyToManyField(blank=True, null=True, to='moviedb.productioncompany')),
            ],
            options={
                'indexes': [
                    models.Index(
                        fields=[
                            '-release_date',
                            '-budget',
                            '-tmdb_popularity',
                            '-immdb_popularity',
                            '-lb_rating',
                            '-lb_watched',
                            '-imdb_rating',
                            '-kp_rating',
                        ],
                        name='moviedb_mov_release_6d9272_idx',
                    )
                ],
            },
        ),
        migrations.RunSQL(sql='CREATE EXTENSION IF NOT EXISTS btree_gin;', reverse_sql='DROP EXTENSION IF EXISTS btree_gin;'),
        migrations.RunSQL(sql='CREATE EXTENSION IF NOT EXISTS pg_trgm;', reverse_sql='DROP EXTENSION IF EXISTS pg_trgm;'),
    ]
