# Generated by Django 5.2.4 on 2025-07-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0002_alter_genre_name_alter_movie_imdb_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='production_company_id',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, to='moviedb.genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='production_companies',
            field=models.ManyToManyField(blank=True, to='moviedb.productioncompany'),
        ),
    ]
