# Generated by Django 5.2.4 on 2025-07-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0005_country_language_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
