# Generated by Django 5.2.4 on 2025-07-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0006_alter_language_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, unique=True),
        ),
    ]
