# Generated by Django 5.2.4 on 2025-07-04 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0007_alter_language_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='origin_country',
            field=models.ManyToManyField(blank=True, related_name='origin_country', to='moviedb.country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='slug',
            field=models.SlugField(blank=True, max_length=130, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='original_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_language', to='moviedb.language'),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='production_countries',
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, max_length=260, unique=True),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='spoken_languages',
        ),
        migrations.AlterField(
            model_name='productioncompany',
            name='slug',
            field=models.SlugField(blank=True, max_length=70, unique=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='production_countries',
            field=models.ManyToManyField(blank=True, related_name='production_countries', to='moviedb.country'),
        ),
        migrations.AddField(
            model_name='movie',
            name='spoken_languages',
            field=models.ManyToManyField(blank=True, related_name='spoken_languages', to='moviedb.language'),
        ),
    ]
