# Generated by Django 5.2.4 on 2025-07-04 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0009_productioncompany_origin_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productioncompany',
            name='origin_country',
        ),
        migrations.AddField(
            model_name='productioncompany',
            name='origin_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_country_company', to='moviedb.country'),
        ),
    ]
