# Generated by Django 5.2.4 on 2025-07-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0011_alter_productioncompany_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='productioncompany',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='productioncompany',
            name='slug',
            field=models.SlugField(blank=True, max_length=260, unique=True),
        ),
    ]
