# Generated by Django 5.2.4 on 2025-07-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0013_alter_country_slug_alter_genre_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioncompany',
            name='logo_path',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
