# Generated by Django 5.2.4 on 2025-07-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0016_alter_movie_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='id',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='tmdb_genre_id',
        ),
        migrations.AddField(
            model_name='genre',
            name='tmdb_id',
            field=models.IntegerField(default=-1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
