# Generated by Django 5.2.4 on 2025-07-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0017_remove_genre_id_remove_genre_tmdb_genre_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='id',
        ),
        migrations.RemoveField(
            model_name='productioncompany',
            name='id',
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productioncompany',
            name='tmdb_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
