# Generated by Django 5.2.4 on 2025-07-07 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0018_remove_movie_id_remove_productioncompany_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='movie',
            name='moviedb_mov_release_6d9272_idx',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='immdb_popularity',
            new_name='imdb_popularity',
        ),
        migrations.AlterField(
            model_name='movie',
            name='backdrop_path',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='movies', to='moviedb.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='origin_country',
            field=models.ManyToManyField(blank=True, related_name='movies_originating_from', to='moviedb.country'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='original_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies_as_original_language', to='moviedb.language'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='original_title',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='movie',
            name='production_companies',
            field=models.ManyToManyField(blank=True, related_name='movies', to='moviedb.productioncompany'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='production_countries',
            field=models.ManyToManyField(blank=True, related_name='movies_produced_in', to='moviedb.country'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='revenue',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='spoken_languages',
            field=models.ManyToManyField(blank=True, related_name='movies_spoken_in', to='moviedb.language'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_popularity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_rating',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_vote_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='productioncompany',
            name='logo_path',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='productioncompany',
            name='origin_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='moviedb.country'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-release_date', '-budget', '-tmdb_popularity', '-imdb_popularity', '-lb_rating', '-lb_watched', '-imdb_rating', '-kp_rating'], name='moviedb_mov_release_7af20d_idx'),
        ),
    ]
