# Generated by Django 5.2.4 on 2025-07-07 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0019_remove_movie_moviedb_mov_release_6d9272_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('tmdb_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('overview', models.TextField(blank=True, default='')),
                ('poster_path', models.CharField(blank=True, default='', max_length=64)),
                ('backdrop_path', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'verbose_name_plural': 'collections',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MovieEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_rating', models.FloatField(blank=True, default=0.0)),
                ('tmdb_vote_count', models.PositiveIntegerField(blank=True, default=0)),
                ('tmdb_popularity', models.PositiveIntegerField(blank=True, default=0)),
                ('lb_rating', models.FloatField(blank=True, null=True)),
                ('lb_vote_count', models.PositiveIntegerField(blank=True, null=True)),
                ('lb_fans', models.PositiveIntegerField(blank=True, null=True)),
                ('lb_watched', models.PositiveIntegerField(blank=True, null=True)),
                ('lb_liked', models.PositiveIntegerField(blank=True, null=True)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('imdb_vote_count', models.PositiveIntegerField(blank=True, null=True)),
                ('imdb_popularity', models.PositiveIntegerField(blank=True, null=True)),
                ('kp_rating', models.FloatField(blank=True, null=True)),
                ('kp_vote_count', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'movie engagement',
                'verbose_name_plural': 'movie engagements',
                'ordering': ['-lb_rating'],
            },
        ),
        migrations.AlterModelOptions(
            name='productioncompany',
            options={'ordering': ['name'], 'verbose_name': 'production company', 'verbose_name_plural': 'production companies'},
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='moviedb_mov_release_7af20d_idx',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='imdb_popularity',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='imdb_rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='imdb_vote_count',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='kp_rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='kp_vote_count',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='lb_fans',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='lb_liked',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='lb_rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='lb_vote_count',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='lb_watched',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tmdb_popularity',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tmdb_rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tmdb_vote_count',
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['name'], name='moviedb_col_name_44da5a_idx'),
        ),
        migrations.AddField(
            model_name='movie',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='moviedb.collection'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title', '-release_date', '-budget', '-revenue', '-runtime'], name='moviedb_mov_title_d570dc_idx'),
        ),
        migrations.AddField(
            model_name='movieengagement',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement', to='moviedb.movie'),
        ),
        migrations.AddIndex(
            model_name='movieengagement',
            index=models.Index(fields=['-tmdb_popularity', '-imdb_popularity', '-lb_rating', '-lb_watched', '-imdb_rating', '-kp_rating'], name='moviedb_mov_tmdb_po_385e45_idx'),
        ),
    ]
