# Generated by Django 5.2.4 on 2025-07-07 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0020_collection_movieengagement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(blank=True, default='', max_length=128)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MovieCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=64)),
                ('job', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('tmdb_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('imdb_id', models.CharField(blank=True, default='', max_length=16)),
                ('known_for_department', models.CharField(blank=True, default='', max_length=64)),
                ('biography', models.TextField(blank=True, default='')),
                ('place_of_birth', models.CharField(blank=True, default='', max_length=256)),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('NB', 'Non-binary')], default='', max_length=2)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('deathday', models.DateField(blank=True, null=True)),
                ('profile_path', models.CharField(blank=True, default='', max_length=64)),
                ('tmdb_popularity', models.PositiveIntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name_plural': 'persons',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='moviedb_mov_title_d570dc_idx',
        ),
        migrations.RemoveIndex(
            model_name='movieengagement',
            name='moviedb_mov_tmdb_po_385e45_idx',
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['slug'], name='moviedb_col_slug_f3d299_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['slug'], name='moviedb_cou_slug_a8ad85_idx'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['slug'], name='moviedb_gen_slug_9d1f34_idx'),
        ),
        migrations.AddIndex(
            model_name='language',
            index=models.Index(fields=['slug'], name='moviedb_lan_slug_cfad6d_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title'], name='moviedb_mov_title_e99fde_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-release_date'], name='moviedb_mov_release_22ecef_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-budget'], name='moviedb_mov_budget_326877_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-revenue'], name='moviedb_mov_revenue_e77b6e_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-runtime'], name='moviedb_mov_runtime_192b41_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['slug'], name='moviedb_mov_slug_1e89a6_idx'),
        ),
        migrations.AddIndex(
            model_name='movieengagement',
            index=models.Index(fields=['-tmdb_popularity'], name='moviedb_mov_tmdb_po_80d0b6_idx'),
        ),
        migrations.AddIndex(
            model_name='movieengagement',
            index=models.Index(fields=['-imdb_popularity'], name='moviedb_mov_imdb_po_719e6b_idx'),
        ),
        migrations.AddIndex(
            model_name='movieengagement',
            index=models.Index(fields=['-lb_rating'], name='moviedb_mov_lb_rati_939278_idx'),
        ),
        migrations.AddIndex(
            model_name='movieengagement',
            index=models.Index(fields=['-lb_watched'], name='moviedb_mov_lb_watc_432b55_idx'),
        ),
        migrations.AddIndex(
            model_name='movieengagement',
            index=models.Index(fields=['-imdb_rating'], name='moviedb_mov_imdb_ra_93a3d9_idx'),
        ),
        migrations.AddIndex(
            model_name='movieengagement',
            index=models.Index(fields=['-kp_rating'], name='moviedb_mov_kp_rati_7b49ed_idx'),
        ),
        migrations.AddIndex(
            model_name='productioncompany',
            index=models.Index(fields=['slug'], name='moviedb_pro_slug_7d36f3_idx'),
        ),
        migrations.AddField(
            model_name='moviecast',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast', to='moviedb.movie'),
        ),
        migrations.AddField(
            model_name='moviecrew',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='moviedb.movie'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['name'], name='moviedb_per_name_6b7553_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['slug'], name='moviedb_per_slug_29c9e3_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['-tmdb_popularity'], name='moviedb_per_tmdb_po_deb6ec_idx'),
        ),
        migrations.AddField(
            model_name='moviecrew',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_roles', to='moviedb.person'),
        ),
        migrations.AddField(
            model_name='moviecast',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_roles', to='moviedb.person'),
        ),
        migrations.AddIndex(
            model_name='moviecrew',
            index=models.Index(fields=['department', 'job'], name='moviedb_mov_departm_16fe10_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='moviecrew',
            unique_together={('movie', 'person', 'job')},
        ),
        migrations.AlterUniqueTogether(
            name='moviecast',
            unique_together={('movie', 'person', 'character')},
        ),
    ]
