# Generated by Django 5.2.4 on 2025-07-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0021_moviecast_moviecrew_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieengagement',
            name='tmdb_popularity',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='person',
            name='tmdb_popularity',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
