# Generated by Django 5.2.4 on 2025-07-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0024_alter_movie_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='imdb_url',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='kp_url',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='lb_url',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tmdb_url',
        ),
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='revenue',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
