# Generated by Django 5.2.4 on 2025-07-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0025_remove_movie_imdb_url_remove_movie_kp_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='revenue',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
