# Generated by Django 5.2.4 on 2025-07-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0026_alter_movie_budget_alter_movie_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecast',
            name='character',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
