# Generated by Django 5.2.4 on 2025-07-08 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0027_alter_moviecast_character_alter_person_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moviecrew',
            unique_together={('movie', 'person', 'department', 'job')},
        ),
    ]
