# Generated by Django 5.2.4 on 2025-07-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0028_alter_moviecrew_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='moviecast',
            name='character',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=512),
        ),
    ]
