# Generated by Django 5.2.4 on 2025-07-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0029_alter_movie_tagline_alter_moviecast_character_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(blank=True, related_name='directed_movies', to='moviedb.person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_documentary',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_short',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_tv_movie',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
