# Generated by Django 5.2.4 on 2025-07-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0031_rename_is_documentary_movie_documentary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name'], 'verbose_name_plural': 'people'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='original_title',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=1024),
        ),
    ]
