# Generated by Django 5.2.4 on 2025-07-11 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0032_alter_person_options_alter_movie_original_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='last_update',
            field=models.DateField(default=datetime.date(2025, 6, 29)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='last_update',
            field=models.DateField(default=datetime.date(2025, 6, 29)),
            preserve_default=False,
        ),
    ]
