# Generated by Django 5.2.4 on 2025-07-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0033_movie_last_update_person_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='last_update',
            field=models.DateField(blank=True),
        ),
    ]
