# Generated by Django 5.2.4 on 2025-07-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0034_alter_movie_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=1024),
        ),
    ]
