# Generated by Django 5.2.4 on 2025-07-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0035_alter_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='moviecast',
            name='character',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
