# Generated by Django 5.2.4 on 2025-07-12 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0036_alter_movie_tagline_alter_moviecast_character'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['name'], 'verbose_name': 'collection', 'verbose_name_plural': 'collections'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'genre', 'verbose_name_plural': 'genres'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name'], 'verbose_name': 'language', 'verbose_name_plural': 'languages'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-release_date'], 'verbose_name': 'movie', 'verbose_name_plural': 'movies'},
        ),
        migrations.AlterModelOptions(
            name='moviecast',
            options={'ordering': ['order'], 'verbose_name': 'cast', 'verbose_name_plural': 'casts'},
        ),
        migrations.AlterModelOptions(
            name='moviecrew',
            options={'verbose_name': 'crew', 'verbose_name_plural': 'crews'},
        ),
        migrations.AlterModelOptions(
            name='movieengagement',
            options={'ordering': ['-lb_rating'], 'verbose_name': 'engagement', 'verbose_name_plural': 'engagements'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name'], 'verbose_name': 'person', 'verbose_name_plural': 'people'},
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='moviedb_mov_budget_326877_idx',
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='moviedb_mov_revenue_e77b6e_idx',
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='moviedb_mov_runtime_192b41_idx',
        ),
    ]
