# Generated by Django 5.2.4 on 2025-07-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0037_alter_collection_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviecast',
            options={'ordering': ['order'], 'verbose_name': 'cast', 'verbose_name_plural': 'cast'},
        ),
        migrations.AlterModelOptions(
            name='moviecrew',
            options={'verbose_name': 'crew', 'verbose_name_plural': 'crew'},
        ),
        migrations.AddField(
            model_name='movie',
            name='status_int',
            field=models.IntegerField(blank=True, choices=[(0, 'Unknown'), (1, 'Canceled'), (2, 'Rumored'), (3, 'Planned'), (4, 'In Production'), (5, 'Post Production'), (6, 'Released')], default=0),
        ),
    ]
