# Generated by Django 5.2.4 on 2025-07-14 15:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0040_rename_status_int_movie_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='last_update',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_update',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
