# Generated by Django 5.2.4 on 2025-07-14 18:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0041_alter_movie_last_update_alter_person_last_update'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='collection',
            name='moviedb_col_name_44da5a_idx',
        ),
        migrations.RemoveIndex(
            model_name='collection',
            name='moviedb_col_slug_f3d299_idx',
        ),
        migrations.RemoveIndex(
            model_name='country',
            name='moviedb_cou_name_7f2602_idx',
        ),
        migrations.RemoveIndex(
            model_name='country',
            name='moviedb_cou_slug_a8ad85_idx',
        ),
        migrations.RemoveIndex(
            model_name='genre',
            name='moviedb_gen_name_4a4077_idx',
        ),
        migrations.RemoveIndex(
            model_name='genre',
            name='moviedb_gen_slug_9d1f34_idx',
        ),
        migrations.RemoveIndex(
            model_name='language',
            name='moviedb_lan_name_e1fe74_idx',
        ),
        migrations.RemoveIndex(
            model_name='language',
            name='moviedb_lan_slug_cfad6d_idx',
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='moviedb_mov_title_e99fde_idx',
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='moviedb_mov_release_22ecef_idx',
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='moviedb_mov_slug_1e89a6_idx',
        ),
        migrations.RemoveIndex(
            model_name='movieengagement',
            name='moviedb_mov_tmdb_po_80d0b6_idx',
        ),
        migrations.RemoveIndex(
            model_name='movieengagement',
            name='moviedb_mov_imdb_po_719e6b_idx',
        ),
        migrations.RemoveIndex(
            model_name='movieengagement',
            name='moviedb_mov_lb_rati_939278_idx',
        ),
        migrations.RemoveIndex(
            model_name='movieengagement',
            name='moviedb_mov_lb_watc_432b55_idx',
        ),
        migrations.RemoveIndex(
            model_name='movieengagement',
            name='moviedb_mov_imdb_ra_93a3d9_idx',
        ),
        migrations.RemoveIndex(
            model_name='movieengagement',
            name='moviedb_mov_kp_rati_7b49ed_idx',
        ),
        migrations.RemoveIndex(
            model_name='person',
            name='moviedb_per_name_6b7553_idx',
        ),
        migrations.RemoveIndex(
            model_name='person',
            name='moviedb_per_slug_29c9e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='person',
            name='moviedb_per_tmdb_po_deb6ec_idx',
        ),
        migrations.RemoveIndex(
            model_name='productioncompany',
            name='moviedb_pro_name_7fb449_idx',
        ),
        migrations.RemoveIndex(
            model_name='productioncompany',
            name='moviedb_pro_slug_7d36f3_idx',
        ),
        migrations.AddField(
            model_name='movie',
            name='created_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='collection',
            name='tmdb_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='genre',
            name='tmdb_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='directed_movies', to='moviedb.person', verbose_name='Directed by'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='movies', to='moviedb.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(db_index=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movieengagement',
            name='lb_rating',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='movieengagement',
            name='lb_watched',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(db_index=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='person',
            name='tmdb_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='tmdb_popularity',
            field=models.FloatField(blank=True, db_index=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='productioncompany',
            name='name',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='productioncompany',
            name='origin_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_companies', to='moviedb.country'),
        ),
        migrations.AlterField(
            model_name='productioncompany',
            name='tmdb_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
