# Generated by Django 5.2.4 on 2025-07-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0042_remove_collection_moviedb_col_name_44da5a_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='person',
            name='created_at',
        ),
    ]
