# Generated by Django 5.2.4 on 2025-07-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0043_remove_movie_created_at_remove_person_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
