# Generated by Django 5.2.4 on 2025-07-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0045_alter_language_name_alter_movie_original_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tmdb_popularity',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
