# Generated by Django 5.2.4 on 2025-07-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0046_movie_tmdb_popularity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-tmdb_popularity'], 'verbose_name': 'movie', 'verbose_name_plural': 'movies'},
        ),
        migrations.AddField(
            model_name='movie',
            name='adult',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='adult',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
