# Generated by Django 5.2.4 on 2025-07-21 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0047_alter_movie_options_movie_adult_person_adult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-tmdb_popularity'], 'verbose_name': 'person', 'verbose_name_plural': 'people'},
        ),
    ]
