# Generated by Django 5.2.4 on 2025-07-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0048_alter_person_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='adult',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
