# Generated by Django 5.2.4 on 2025-07-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0049_collection_adult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='adult',
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
    ]
