# Generated by Django 5.2.4 on 2025-07-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0050_alter_movie_adult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='adult',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-adult'], name='moviedb_mov_adult_14eec7_idx'),
        ),
    ]
