# Generated by Django 5.2.4 on 2025-07-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0052_remove_movie_moviedb_mov_adult_14eec7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productioncompany',
            name='movie_count',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='productioncompany',
            index=models.Index(fields=['name', 'tmdb_id'], name='moviedb_pro_name_a6e6aa_idx'),
        ),
    ]
