# Generated by Django 5.2.4 on 2025-07-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0053_productioncompany_movie_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productioncompany',
            options={'ordering': ['-movie_count'], 'verbose_name': 'production company', 'verbose_name_plural': 'production companies'},
        ),
        migrations.RemoveIndex(
            model_name='productioncompany',
            name='moviedb_pro_name_a6e6aa_idx',
        ),
        migrations.AddField(
            model_name='collection',
            name='avg_popularity',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='collection',
            name='movies_released',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(blank=True, related_name='directed_movies', to='moviedb.person', verbose_name='Directed by'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='movies', to='moviedb.genre'),
        ),
        migrations.AlterField(
            model_name='movieengagement',
            name='lb_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movieengagement',
            name='lb_watched',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
