# Generated by Django 5.2.4 on 2025-07-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0054_alter_productioncompany_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='avg_popularity',
            field=models.FloatField(blank=True, db_index=True, default=0.0),
        ),
    ]
