# Generated by Django 5.2.4 on 2025-07-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0055_alter_collection_avg_popularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioncompany',
            name='movie_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddIndex(
            model_name='productioncompany',
            index=models.Index(fields=['-movie_count'], name='moviedb_pro_movie_c_d22068_idx'),
        ),
    ]
