# Generated by Django 5.2.4 on 2025-07-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0056_alter_productioncompany_movie_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['-avg_popularity'], 'verbose_name': 'collection', 'verbose_name_plural': 'collections'},
        ),
        migrations.AlterField(
            model_name='collection',
            name='avg_popularity',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='collection',
            name='movies_released',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='productioncompany',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['adult', 'movies_released', '-avg_popularity'], name='moviedb_col_adult_270d58_idx'),
        ),
    ]
