# Generated by Django 5.2.4 on 2025-07-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0057_alter_collection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='person',
            name='tmdb_popularity',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['-tmdb_popularity'], name='moviedb_per_tmdb_po_deb6ec_idx'),
        ),
    ]
