# Generated by Django 5.2.4 on 2025-07-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0058_alter_person_name_alter_person_tmdb_popularity_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['adult', '-tmdb_popularity'], name='moviedb_per_adult_1858b1_idx'),
        ),
    ]
