# Generated by Django 5.2.4 on 2025-07-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0059_person_moviedb_per_adult_1858b1_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='person',
            name='moviedb_per_adult_1858b1_idx',
        ),
        migrations.AlterField(
            model_name='person',
            name='adult',
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
    ]
