# Generated by Django 5.2.4 on 2025-07-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0060_remove_person_moviedb_per_adult_1858b1_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='person',
            name='moviedb_per_tmdb_po_deb6ec_idx',
        ),
        migrations.AlterField(
            model_name='person',
            name='adult',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['adult', '-tmdb_popularity'], name='moviedb_per_adult_1858b1_idx'),
        ),
    ]
