# Generated by Django 5.2.4 on 2025-07-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0061_remove_person_moviedb_per_tmdb_po_deb6ec_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviecast',
            options={'verbose_name': 'cast', 'verbose_name_plural': 'cast'},
        ),
        migrations.AlterModelOptions(
            name='movieengagement',
            options={'verbose_name': 'engagement', 'verbose_name_plural': 'engagements'},
        ),
        migrations.RemoveIndex(
            model_name='moviecrew',
            name='moviedb_mov_departm_16fe10_idx',
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='person',
            name='adult',
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
    ]
