# Generated by Django 5.2.4 on 2025-07-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0062_alter_moviecast_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='adult',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
