# Generated by Django 5.2.4 on 2025-07-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0063_alter_person_adult'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cast_roles_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='crew_roles_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
