# Generated by Django 5.2.4 on 2025-07-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0064_person_cast_roles_count_person_crew_roles_count'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['adult', '-cast_roles_count'], name='moviedb_per_adult_80b87c_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['adult', '-crew_roles_count'], name='moviedb_per_adult_28202f_idx'),
        ),
    ]
