# Generated by Django 5.2.4 on 2025-07-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0065_person_moviedb_per_adult_80b87c_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['adult', '-tmdb_popularity'], name='moviedb_mov_adult_16e8f0_idx'),
        ),
    ]
