# Generated by Django 5.2.4 on 2025-07-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0066_movie_moviedb_mov_adult_16e8f0_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-tmdb_popularity'], name='moviedb_mov_tmdb_po_d90bde_idx'),
        ),
    ]
