# Generated by Django 5.2.4 on 2025-07-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0067_movie_moviedb_mov_tmdb_po_d90bde_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['adult', '-release_date'], name='moviedb_mov_adult_4b517c_idx'),
        ),
    ]
