# Generated by Django 5.2.4 on 2025-07-23 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0069_movie_moviedb_mov_adult_eb6c89_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='movie',
            name='moviedb_mov_adult_eb6c89_idx',
        ),
    ]
