# Generated by Django 5.2.4 on 2025-07-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0071_movie_moviedb_mov_adult_eb6c89_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['adult', 'known_for_department', '-tmdb_popularity'], name='moviedb_per_adult_4cbfa5_idx'),
        ),
    ]
