# Generated by Django 5.2.4 on 2025-07-24 17:38

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0072_person_moviedb_per_adult_4cbfa5_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='collection',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name', 'overview'], name='moviedb_col_name_0c2e13_gin'),
        ),
    ]
