# Generated by Django 5.2.4 on 2025-07-24 17:41

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0073_collection_moviedb_col_name_0c2e13_gin'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='collection',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='name_collection_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
