# Generated by Django 5.2.4 on 2025-07-24 19:02

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0074_collection_name_collection_gin_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='collection',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.SearchVector('name', config='english', weight='A'), '||', django.contrib.postgres.search.SearchVector('overview', config='english', weight='B'), django.contrib.postgres.search.SearchConfig('english')), name='moviedb_collection_fts_idx'),
        ),
    ]
