# Generated by Django 5.2.4 on 2025-07-24 19:21

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0075_collection_moviedb_collection_fts_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='collection',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='moviedb_col_name_f34912_gin'),
        ),
    ]
