# Generated by Django 5.2.4 on 2025-07-24 19:29

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0076_collection_moviedb_col_name_f34912_gin'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='collection',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('name', config='english'), name='test_name_fts_idx'),
        ),
    ]
