# Generated by Django 5.2.4 on 2025-07-24 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0077_collection_test_name_fts_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='collection',
            name='moviedb_col_name_0c2e13_gin',
        ),
        migrations.RemoveIndex(
            model_name='collection',
            name='name_collection_gin_idx',
        ),
        migrations.RemoveIndex(
            model_name='collection',
            name='moviedb_collection_fts_idx',
        ),
        migrations.RemoveIndex(
            model_name='collection',
            name='moviedb_col_name_f34912_gin',
        ),
        migrations.RemoveIndex(
            model_name='collection',
            name='test_name_fts_idx',
        ),
    ]
