# Generated by Django 5.2.4 on 2025-07-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0078_remove_collection_moviedb_col_name_0c2e13_gin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='removed_from_tmdb',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='removed_from_tmdb',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
