# Generated by Django 5.2.4 on 2025-07-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0079_movie_removed_from_tmdb_person_removed_from_tmdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='removed_from_tmdb',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='productioncompany',
            name='removed_from_tmdb',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
