# Generated by Django 5.2.4 on 2025-07-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0080_collection_removed_from_tmdb_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='movie',
            name='moviedb_mov_adult_16e8f0_idx',
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='moviedb_mov_tmdb_po_d90bde_idx',
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='moviedb_mov_adult_4b517c_idx',
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='moviedb_mov_adult_eb6c89_idx',
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['removed_from_tmdb', '-tmdb_popularity'], name='moviedb_mov_removed_1fc4b5_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['removed_from_tmdb', 'adult', '-tmdb_popularity'], name='moviedb_mov_removed_c439e6_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['removed_from_tmdb', 'adult', '-release_date'], name='moviedb_mov_removed_8c9b8e_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['removed_from_tmdb', 'adult', '-tmdb_popularity', '-release_date'], name='moviedb_mov_removed_c513e8_idx'),
        ),
    ]
