# Generated by Django 5.2.4 on 2025-07-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0081_remove_movie_moviedb_mov_adult_16e8f0_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-tmdb_popularity'], name='moviedb_mov_tmdb_po_d90bde_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['removed_from_tmdb', 'adult'], name='moviedb_mov_removed_6c58d1_idx'),
        ),
    ]
