# Generated by Django 5.2.4 on 2025-07-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0082_movie_moviedb_mov_tmdb_po_d90bde_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='collection',
            name='moviedb_col_adult_270d58_idx',
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='moviedb_mov_removed_6c58d1_idx',
        ),
        migrations.RemoveIndex(
            model_name='person',
            name='moviedb_per_adult_1858b1_idx',
        ),
        migrations.RemoveIndex(
            model_name='person',
            name='moviedb_per_adult_80b87c_idx',
        ),
        migrations.RemoveIndex(
            model_name='person',
            name='moviedb_per_adult_28202f_idx',
        ),
        migrations.RemoveIndex(
            model_name='person',
            name='moviedb_per_adult_4cbfa5_idx',
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['-avg_popularity'], name='moviedb_col_avg_pop_6dd605_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['removed_from_tmdb', 'adult', 'movies_released', '-avg_popularity'], name='moviedb_col_removed_fbec73_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['-tmdb_popularity'], name='moviedb_per_tmdb_po_deb6ec_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['removed_from_tmdb', 'adult', '-tmdb_popularity'], name='moviedb_per_removed_b2823d_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['removed_from_tmdb', 'adult', '-cast_roles_count'], name='moviedb_per_removed_387027_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['removed_from_tmdb', 'adult', '-crew_roles_count'], name='moviedb_per_removed_3a2eaa_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['removed_from_tmdb', 'adult', 'known_for_department', '-tmdb_popularity'], name='moviedb_per_removed_b49302_idx'),
        ),
        migrations.AddIndex(
            model_name='productioncompany',
            index=models.Index(fields=['removed_from_tmdb', '-movie_count'], name='moviedb_pro_removed_039928_idx'),
        ),
    ]
