# Generated by Django 5.2.4 on 2025-07-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0083_remove_collection_moviedb_col_adult_270d58_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='removed_from_tmdb',
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
    ]
