# Generated by Django 5.2.4 on 2025-07-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0084_alter_person_removed_from_tmdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='removed_from_tmdb',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
