# Generated by Django 5.2.4 on 2025-07-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0085_alter_person_removed_from_tmdb'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['removed_from_tmdb', 'adult'], name='moviedb_mov_removed_6c58d1_idx'),
        ),
    ]
