# Generated by Django 5.2.4 on 2025-07-27 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0086_movie_moviedb_mov_removed_6c58d1_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='movie',
            name='moviedb_mov_removed_6c58d1_idx',
        ),
    ]
