# Generated by Django 5.2.4 on 2025-07-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0087_remove_movie_moviedb_mov_removed_6c58d1_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='productioncompany',
            name='adult',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
