# Generated by Django 5.2.4 on 2025-07-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0088_productioncompany_adult'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productioncompany',
            index=models.Index(fields=['removed_from_tmdb', 'adult', '-movie_count'], name='moviedb_pro_removed_edd439_idx'),
        ),
    ]
