# Generated by Django 5.2.4 on 2025-07-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0089_productioncompany_moviedb_pro_removed_edd439_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='alias_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
