# Generated by Django 5.2.4 on 2025-07-30 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0090_country_alias_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='directors',
        ),
    ]
